const SOCKET = {
  EVENT_AUTH_SUCCESS: "EVENT_AUTH_SUCCESS",
  EVENT_AUTH_FAIL: "EVENT_AUTH_FAIL",

  EVENT_CONNECTION_SUCCESS: "EVENT_CONNECTION_SUCCESS",
  EVENT_CONNECTION_FAIL: "EVENT_CONNECTION_FAIL",

  COMMAND_REQUEST_AI_DATA: "COMMAND_REQUEST_AI_DATA",
  EVENT_RECEIVE_AI_DATA: "EVENT_RECEIVE_AI_DATA",

  COMMAND_REQUEST_COLLECTION: "COMMAND_REQUEST_COLLECTION",
  EVENT_RECEIVE_COLLECTION: "EVENT_RECEIVE_COLLECTION",

  COMMAND_SEND_BROADCAST: "COMMAND_SEND_BROADCAST",
  EVENT_RECEIVE_BROADCAST: "EVENT_RECEIVE_BROADCAST",

  COMMAND_SEND_PRIVATE_MESSAGE: "COMMAND_SEND_PRIVATE_MESSAGE",
  EVENT_RECEIVE_PRIVATE_MESSAGE: "EVENT_RECEIVE_PRIVATE_MESSAGE",

  COMMAND_COLLECTION_ADD_ITEM: "COMMAND_COLLECTION_ADD_ITEM",
  EVENT_COLLECTION_ADD_ITEM: "EVENT_COLLECTION_ADD_ITEM",

  COMMAND_COLLECTION_REMOVE_ITEM: "COMMAND_COLLECTION_REMOVE_ITEM",
  EVENT_COLLECTION_REMOVE_ITEM: "EVENT_COLLECTION_REMOVE_ITEM",

  COMMAND_COLLECTION_UPDATE_ITEM: "COMMAND_COLLECTION_UPDATE_ITEM",
  EVENT_COLLECTION_UPDATE_ITEM: "EVENT_COLLECTION_UPDATE_ITEM",

  COMMAND_UPDATE: "COMMAND_UPDATE",
  EVENT_UPDATE: "EVENT_UPDATE",

  COMMAND_DISCONNECT: "COMMAND_DISCONNECT",

  COMMAND_REQUEST_API: "COMMAND_REQUEST_API",
  EVENT_RECEIVE_API: "EVENT_RECEIVE_API",

  EVENT_USER: "EVENT_USER",
  EVENT_CONNECTION: "connection",
  EVENT_OPEN: "open",
  EVENT_DISCONNECT: "disconnect",
  EVENT_ERROR: "EVENT_ERROR",
}

module.exports = SOCKET
